### ISSUE TITLE
[PE-D][Tester E] app allows duplicate contact entries with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-4/tp#264] opened 2024-11-08 16:48 UTC
The add command is supposed to only allow for adding of contacts with unique names. However it does not currently seem to able to handle case-insensitive inputs. 

Currently I am able to add in multiple duplicate contacts as long as I change the capitalization of the names 

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/fed7e098-1c6e-407a-a4c7-77ef477cba15.png)

This differs from the expected behavior of the add command, which is that I am only supposed to be able to add in a contact with a unique name, while duplicate names are rejected.

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/2322252f-8e81-4d21-9712-ef27cb4f16b8.png)\

Steps taken to replicate:
1. add n/name1
2. add n/NAME1

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: volleyballkickedme/ped#1

**Comment by ChenLeiyu** [comment] 2024-11-09 09:57
duplicate of #256

**Closed by ChenLeiyu** 2024-11-09 09:57 UTC
