### ISSUE TITLE
[PE-D][Tester B] Clicking on exit or help shows a blank dropdown

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-4/tp#275] opened 2024-11-08 18:47 UTC
Clicking on exit or help shows a blank dropdown and the options cannot be scene unless I hover over them. This is perhaps because the UI shows the options in white text instead of black text. 

Unfortunately, I am not being able to take a screenshot of this because the dropdown closes when I try to take a screenshot.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: T1duS/ped#4

**Comment by ChenLeiyu** [comment] 2024-11-09 10:29
Duplicate of #258

**Closed by ChenLeiyu** 2024-11-09 10:29 UTC
