### ISSUE TITLE
[PE-D][Tester E] Images in User Guide do not match application interface

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-4/tp#292] opened 2024-11-08 23:06 UTC
The screenshots used in the User Guide do not reflect the interface of the application

User Guide:
![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/17697b6d-8cae-440c-8f6f-68eca735f92c.png)

Application UI:

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/4ad8b1ee-e042-4472-ba03-88060fa28dfc.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: volleyballkickedme/ped#8

**Comment by ChenLeiyu** [comment] 2024-11-09 10:49
duplicate of #259

**Closed by ChenLeiyu** 2024-11-09 10:49 UTC
