### ISSUE TITLE
[PE-D][Tester E] Incorrect state after undo command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-4/tp#296] opened 2024-11-08 23:12 UTC
The incorrect state is displayed after the `undo` command is executed in the following scenario.

First the user executes the `find` command to show a filtered list of contacts

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/f36b38ef-f42a-44fb-a4cc-3dea6c26d9f8.png)

Next the user adds a contact with the `add` command

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/d9c1e6bd-0100-483f-a373-a8487e85e056.png)

This will cause the UI to display all contacts currently in the list, including the most recently added contact.

Executing the `undo` command will cause the list to revert back to the filtered list displayed from the find command, which may cause confusion among users since it is expected to simply undo the `add` command and display all contacts in the list without the newly added contact.

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/1641ab7e-6928-4fdd-8e33-27bdeea86911.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: volleyballkickedme/ped#9

**Comment by ChenLeiyu** [comment] 2024-11-09 11:04
This is intentional and done so that multiple undos are supported. We want "undo" to revert to the exact same state, including the displayed list.
This could be stated more clearly in the User Guide.

**Comment by JJtan2002** [comment] 2024-11-11 16:11
Closed as an enhancement, not a bug.

**Closed by JJtan2002** 2024-11-11 16:11 UTC
Labels: severity.Medium, type.UG, type.Feature
